### ISSUE TITLE
Cannot install Arctic on MacOS M2 Arm processor

### ISSUE THREAD

**Issue by flemmel** [jkeger/arctic#44]
Hello everybody,

I discovered that it's not possible to install Arctic on a MacBook computer with a M1/M2 Arm processor.

**What happened:**
During the installation process, the `autoconf` package version 2022.7.11.1 is installed (see https://github.com/jkeger/arctic/blob/750bdfb07c39295aa225af964620b1b106a1e5bd/pyproject.toml#L19). 

Unfortunately, this package is installing `pyyaml` version 5.4.1 which is definitely not compatible with a M1/M2 Arm processor.

**Possible solution:**

Using package `autoconf` version 2023.9.18.4 solves the issue. This package will install `pyyaml` version >=6.0.1 which is compatible with a M1/M2 Arm processor.

See the following code snippet to fix the issue in `pyproject.toml`:

```toml
dependencies = [
    "autoconf==2023.9.18.4",     # <= This is new
    "numpy ~=1.21",
]
```

Cheers,
Frederic
